version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    expose:
      - "9000"
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    networks:
      - inception
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./requirements/mariadb/conf:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecure
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    networks:
      - inception

volumes:
  mariadb-data:

networks:
  inception:
    driver: bridge

