CREATE DATABASE IF NOT EXISTS `wordpress`;

CREATE USER IF NOT EXISTS 'ryusupov'@'%' IDENTIFIED BY 'ryusupov';

GRANT ALL PRIVILEGES ON `wordpress`.* TO 'ryusupov'@'%';

FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root' WITH GRANT OPTION;

FLUSH PRIVILEGES;

